baseURL = "https://lisianthuss.github.io"
languageCode = "en-us"
title = "잠들지 않는 시간"
theme="inkblotty"

sectionPagesMenu = "main"

[menu]
    [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = 0
